# Generated by Django 6.0.7 on 2026-08-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nike', '0003_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
    ]
