# Generated by Django 6.0.7 on 2026-07-11 13:59

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='no value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='null value', max_length=100),
            preserve_default=False,
        ),
        # migrations.AddField(
        #             model_name='user',
        #             name='email',
        #             field=models.EmailField(default='abc@gmail.com', max_length=100),
        #             preserve_default=False,
        #         ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True),
        )]
